name: Update README with new joke

on:
  schedule:
    # Runs every hour
    - cron: '0 * * * *'
  workflow_dispatch: # Allows you to run this workflow manually from the Actions tab

jobs:
  update-readme:
    runs-on: ubuntu-latest

    permissions:
      contents: write
    steps:
      # Step 1: Check out your repository code
      - name: Check out repo
        uses: actions/checkout@v4

      # Step 2: Fetch joke and update README using a Python script
      - name: Update README with a joke
        run: |
          # Fetch the joke and store it in a GitHub environment variable
          echo "JOKE_TEXT=$(curl -s 'https://v2.jokeapi.dev/joke/Any?blacklistFlags=nsfw,racist,sexist,explicit&type=single' | jq -r '.joke')" >> $GITHUB_ENV
          
          # Run the Python script to safely replace the text in the README
          python - <<EOF
          import re
          import os

          readme_path = "README.md"
          joke_text = os.getenv("JOKE_TEXT")
          
          with open(readme_path, "r") as file:
              content = file.read()
          
          # Use a robust regex to find and replace the block
          replacement_text = f"\n> {joke_text}\n"
          new_content = re.sub(r".*", replacement_text, content, flags=re.DOTALL)
          
          with open(readme_path, "w") as file:
              file.write(new_content)
          EOF

      # Step 3: Commit the changes back to your repository
      - name: Commit and push if changed
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "BOT: Update random joke"
          commit_user_name: "GitHub Actions Bot"
          commit_user_email: "actions@github.com"
          commit_author: "GitHub Actions Bot <actions@github.com>"