name: Update README with new joke

on:
  schedule:
    # Runs every hour
    - cron: '0 * * * *'
  workflow_dispatch: # Allows you to run this workflow manually from the Actions tab

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      # Step 1: Check out your repository code
      - name: Check out repo
        uses: actions/checkout@v4

      # Step 2: Fetch a joke using curl and update the README
      - name: Update README with a joke
        # This command fetches the joke, extracts the 'joke' text,
        # and replaces the content between the JOKE_START/JOKE_END tags in the README.
        run: |
          JOKE_TEXT=$(curl -s 'https://v2.jokeapi.dev/joke/Any?blacklistFlags=nsfw,racist,sexist,explicit&type=single' | jq -r '.joke')
          sed -i '//,//c\\n> '"$JOKE_TEXT"'\n' README.md

      # Step 3: Commit the changes back to your repository
      - name: Commit and push if changed
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "BOT: Update random joke"
          commit_user_name: "GitHub Actions Bot"
          commit_user_email: "actions@github.com"
          commit_author: "GitHub Actions Bot <actions@github.com>"